name: Byte Burner Integration

on:
  push:
    branches: [ main ]
    paths: [ src/client/**, src/net_iot/** ]
  workflow_dispatch:

jobs:
  build-ubuntu-dist:
    uses: ./.github/workflows/byte-burner-ubuntu-build.yml
    secrets: inherit
  build-darwin-dist:
    uses: ./.github/workflows/byte-burner-darwin-build.yml
    secrets: inherit
  build-windows-dist:
    uses: ./.github/workflows/byte-burner-windows-build.yml
    secrets: inherit