name: Byte Burner Integration

on:
  push:
    branches: [ main ]
    paths: [ src/client/**, src/net_iot/** ]
  workflow_dispatch:

jobs:
  build-debian-x64-dist:
    uses: ./.github/workflows/byte-burner-debian-x64-build.yml
    secrets: inherit
  build-debian-arm64-dist:
    uses: ./.github/workflows/byte-burner-debian-arm64-build.yml
    secrets: inherit
  build-darwin-dist:
    uses: ./.github/workflows/byte-burner-darwin-x64-arm64-build.yml
    secrets: inherit
  build-windows-dist:
    uses: ./.github/workflows/byte-burner-windows-x64-arm64-build.yml
    secrets: inherit