name: Byte Burner Debian (Arm64) Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-debian-arm64:
    runs-on: ARM64
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1

      - name: Print node version
        run: |
          echo "*****************************************"
          node --version
          echo "*****************************************"

      - name: Print npm version
        run: |
          echo "*****************************************"
          npm --version
          echo "*****************************************"

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.100'

      - name: Print dotnet version
        run: |
          echo "*****************************************"
          dotnet --version
          echo "*****************************************"

      - name: Setup python3
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install python3.12 -y
          source ~/.profile
          source ~/.bashrc

      - name: Print python3 version
        run: |
          echo "*****************************************"
          python3 --version
          echo "*****************************************"

      - name: Print pip version
        run: |
          echo "*****************************************"
          pip --version
          echo "*****************************************"

      - name: Install python 'setuptools' library for native node module deps to work in electron
        run: |
          pip install setuptools

      - name: Build Electron App (Arm64)
        run: |
          cd src/scripts
          ./unix-build.sh

      - name: Upload Byte Burner To Digital Ocean Spaces (Arm64)
        uses: BetaHuhn/do-spaces-action@latest
        with:
          access_key: ${{ secrets.ACCESS_KEY}}
          secret_key: ${{ secrets.SECRET_KEY }}
          space_name: ${{ secrets.SPACES_NAME }}
          space_region: ${{ secrets.SPACES_REGION }}
          source: src/client/out/make/deb/arm64/byte-burner_1.0.0_arm64.deb
          out_dir: arm64

